#!/usr/bin/env node
/**
 * workspace-to-prod.cjs — Cowork workspace JSON files → prod-D1 SQL inserts
 * 2026-05-09
 *
 * Different from the original agency-import.cjs:
 *   - Maps workspace client_ids (kamz-inkzone, aish-is-live, etc.) to the
 *     prod-D1 IDs (c-1769783528025-..., c-1769802065138-...) BEFORE inserting
 *   - Does NOT INSERT INTO clients (prod already has those rows aligned)
 *   - Adds client_channels rows (the multi-channel data we have)
 *   - Inserts competitors / competitor_history / seo_history / daily_research /
 *     niche_calendars with the right prod IDs
 *
 * Usage:
 *   node worker/migrations/workspace-to-prod.cjs \
 *     --workspace "../../" \
 *     --out worker/migrations/workspace-to-prod.sql
 *
 *   cd worker
 *   npx wrangler d1 execute shinel-db --remote --file migrations/workspace-to-prod.sql
 */

const fs = require("fs");
const path = require("path");

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, cur, i, arr) => {
    if (cur.startsWith("--")) acc.push([cur.slice(2), arr[i + 1]]);
    return acc;
  }, [])
);
const WORKSPACE = path.resolve(args.workspace || "../../");
const OUT_FILE = args.out || "workspace-to-prod.sql";

// Workspace ID → prod D1 client ID mapping. Built from the SELECT we ran
// earlier; if you ever change a prod client ID, update here.
const ID_MAP = {
  "kamz-inkzone":         "c-1769783528025-accl7vadsl",
  "aish-is-live":         "c-1769802065138-4rnx69bni5s",
  "gamify-with-anchit":   "c-1769795052179-stnyxjmqbz9",
  "kiaraa-gaming":        "c-1769802499809-xwapop8353",
  "kundan-parashar":      "c-1769794849355-34851lo1g0p",
};

const CLIENTS_DIR = path.join(WORKSPACE, "clients");
const LIB_DIR = path.join(WORKSPACE, "lib");
const REGISTRY = path.join(WORKSPACE, "registry.json");

if (!fs.existsSync(WORKSPACE)) {
  console.error(`workspace not found: ${WORKSPACE}`);
  process.exit(1);
}

function sql(strings, ...values) {
  return strings.reduce((a, s, i) => a + s + (i < values.length ? esc(values[i]) : ""), "");
}
function esc(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  if (v instanceof Date) return `'${v.toISOString()}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}
function readJSON(p) { try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch { return null; } }
function readJSONL(p) {
  if (!fs.existsSync(p)) return [];
  return fs.readFileSync(p, "utf8")
    .split("\n").filter(l => l.trim().length > 1)
    .map(l => { try { return JSON.parse(l); } catch { return null; } })
    .filter(Boolean);
}
function readMD(p) { return fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null; }
function uuid() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, c => {
    const r = (Math.random() * 16) | 0;
    return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
  });
}

const out = [];
const stats = { channels: 0, competitors: 0, comp_history: 0, seo: 0, research: 0, calendars: 0, skipped: 0 };

out.push("-- workspace-to-prod.sql — auto-generated by workspace-to-prod.cjs");
out.push(`-- Generated: ${new Date().toISOString()}`);
out.push(`-- Source: ${WORKSPACE}`);
out.push(`-- Maps workspace client_ids → prod D1 client_ids before inserting.`);
out.push(`-- NOTE: D1 wrangler wraps the file in an implicit transaction; do NOT add`);
out.push(`-- explicit BEGIN/COMMIT (D1 rejects them).`);
out.push("");

// Resolve workspace client_id → prod client_id using ID_MAP
function prodId(wsId) {
  const m = ID_MAP[wsId];
  if (!m) {
    stats.skipped++;
    return null;
  }
  return m;
}

const registry = readJSON(REGISTRY);

// 1. client_channels — multi-channel YT data we have for each tracked client
out.push("-- ---- client_channels ----");
for (const c of registry?.clients || []) {
  const targetId = prodId(c.id);
  if (!targetId) {
    out.push(`-- (skip) workspace client_id "${c.id}" has no prod mapping; skipping channels`);
    continue;
  }
  const data = readJSON(path.join(CLIENTS_DIR, c.id, "channels.json"));
  if (!data?.channels) continue;
  for (const ch of data.channels) {
    out.push(sql`INSERT OR IGNORE INTO client_channels
      (id, client_id, channel_id, handle, url, role, language, niche_tag_override, studio_url, active, notes, created_at, updated_at)
      VALUES (${uuid()}, ${targetId}, ${ch.channel_id}, ${ch.handle || null}, ${ch.url || null}, ${ch.role || "main"}, ${ch.language || null}, ${ch.niche_tag_override || null}, ${ch.studio_url || null}, ${ch.active === false ? 0 : 1}, ${ch.notes || null}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`);
    stats.channels++;
  }
}
out.push("");

// 2. competitors
out.push("-- ---- competitors ----");
for (const c of registry?.clients || []) {
  const targetId = prodId(c.id);
  if (!targetId) continue;
  const data = readJSON(path.join(CLIENTS_DIR, c.id, "competitors.json"));
  if (!data) continue;
  const lists = [...(data.competitors || []), ...(data.tattoo_competitors || []), ...(data.music_competitors || [])];
  for (const comp of lists) {
    out.push(sql`INSERT OR IGNORE INTO competitors
      (client_id, channel_id, name, tier, niche_tag, initial_subs, initial_video_count, notes, active, created_at, updated_at)
      VALUES (${targetId}, ${comp.channel_id}, ${comp.name}, ${comp.tier || null}, ${data.niche || c.niche_tag || null}, ${comp.subs || 0}, ${comp.video_count || 0}, ${comp.notes || null}, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`);
    stats.competitors++;
  }
}
out.push("");

// 3. competitor_history
out.push("-- ---- competitor_history ----");
for (const c of registry?.clients || []) {
  const targetId = prodId(c.id);
  if (!targetId) continue;
  const rows = readJSONL(path.join(CLIENTS_DIR, c.id, "competitor-history.jsonl"));
  for (const r of rows) {
    out.push(sql`INSERT OR IGNORE INTO competitor_history
      (client_id, channel_id, captured_date, subs, video_count, view_count, recent_uploads_json, median_recent_views, overperformers_json, captured_at)
      VALUES (${targetId}, ${r.channel_id}, ${r.date}, ${r.subs || 0}, ${r.video_count || 0}, ${r.view_count || 0}, ${JSON.stringify(r.recent_5_uploads || [])}, ${r.median_recent_views || 0}, ${JSON.stringify(r.overperformers || [])}, CURRENT_TIMESTAMP);`);
    stats.comp_history++;
  }
}
out.push("");

// 4. seo_history
out.push("-- ---- seo_history ----");
for (const c of registry?.clients || []) {
  const targetId = prodId(c.id);
  if (!targetId) continue;
  const rows = readJSONL(path.join(CLIENTS_DIR, c.id, "seo-history.jsonl"));
  for (const r of rows) {
    out.push(sql`INSERT OR IGNORE INTO seo_history
      (client_id, asset_type, video_id, action, old_title, old_description_first_line, old_tags_count, old_tags_chars, new_title, new_description_first_line, new_tags_count, new_tags_chars, changes_summary, approved_by, applied_method, applied, applied_at, verified_via, notes, payload_json, created_at)
      VALUES (${targetId}, ${r.type || "upload"}, ${r.video_id || r.stream_id || null}, ${r.action || "reseo"}, ${r.old?.title || null}, ${r.old?.description_first_line || r.old?.description_first_5 || null}, ${r.old?.tags_count || 0}, ${r.old?.tags_chars || 0}, ${r.new?.title || null}, ${r.new?.description_first_line || r.new?.description_first_5 || null}, ${r.new?.tags_count || 0}, ${r.new?.tags_chars || 0}, ${r.changes_summary || null}, ${r.approved_by || null}, ${r.applied_method || null}, ${r.applied === true || r.applied === 1 ? 1 : 0}, ${typeof r.applied_at === "string" ? r.applied_at : null}, ${r.verified_via || null}, ${r.notes || null}, ${JSON.stringify(r)}, ${r.timestamp || "CURRENT_TIMESTAMP"});`);
    stats.seo++;
  }
}
out.push("");

// 5. daily_research
out.push("-- ---- daily_research ----");
for (const c of registry?.clients || []) {
  const targetId = prodId(c.id);
  if (!targetId) continue;
  const dir = path.join(CLIENTS_DIR, c.id, "research");
  if (!fs.existsSync(dir)) continue;
  for (const fn of fs.readdirSync(dir)) {
    const m = fn.match(/^(\d{4}-\d{2}-\d{2})\.md$/);
    if (!m) continue;
    const content = readMD(path.join(dir, fn));
    out.push(sql`INSERT OR IGNORE INTO daily_research
      (client_id, research_date, schema_version, content_md, generated_at)
      VALUES (${targetId}, ${m[1]}, 2, ${content}, CURRENT_TIMESTAMP);`);
    stats.research++;
  }
}
out.push("");

// 6. niche_calendars (no client mapping needed)
out.push("-- ---- niche_calendars ----");
const calsDir = path.join(LIB_DIR, "calendars");
if (fs.existsSync(calsDir)) {
  for (const fn of fs.readdirSync(calsDir)) {
    if (!fn.endsWith(".md")) continue;
    const niche = fn.replace(/\.md$/, "");
    const content = readMD(path.join(calsDir, fn));
    out.push(sql`INSERT OR REPLACE INTO niche_calendars (niche_tag, config_md, updated_at) VALUES (${niche}, ${content}, CURRENT_TIMESTAMP);`);
    stats.calendars++;
  }
}
out.push("");

out.push("");
out.push(`-- Stats: ${JSON.stringify(stats)}`);

fs.writeFileSync(OUT_FILE, out.join("\n"));

console.log(`✓ Wrote ${OUT_FILE}`);
console.log(`  ${out.length} lines, ${(fs.statSync(OUT_FILE).size / 1024).toFixed(1)} KB`);
console.log(`  Stats:`, stats);
console.log(``);
console.log(`Next:`);
console.log(`  cd worker && npx wrangler d1 execute shinel-db --remote --file migrations/workspace-to-prod.sql`);
